[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "18"

[build]
  publish = "docs/dist"
  command = "pnpm install && pnpm -w run deploy"

[functions]
  node_bundler = "esbuild"
