/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LeoButton {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        "size": string;
        "type": string;
    }
    interface LeoCard {
        "first": string;
    }
    interface LeoDemo {
    }
    interface LeoForm {
        "first": string;
    }
    interface LeoSearch {
        "first": string;
    }
}
declare global {
    interface HTMLLeoButtonElement extends Components.LeoButton, HTMLStencilElement {
    }
    var HTMLLeoButtonElement: {
        prototype: HTMLLeoButtonElement;
        new (): HTMLLeoButtonElement;
    };
    interface HTMLLeoCardElement extends Components.LeoCard, HTMLStencilElement {
    }
    var HTMLLeoCardElement: {
        prototype: HTMLLeoCardElement;
        new (): HTMLLeoCardElement;
    };
    interface HTMLLeoDemoElement extends Components.LeoDemo, HTMLStencilElement {
    }
    var HTMLLeoDemoElement: {
        prototype: HTMLLeoDemoElement;
        new (): HTMLLeoDemoElement;
    };
    interface HTMLLeoFormElement extends Components.LeoForm, HTMLStencilElement {
    }
    var HTMLLeoFormElement: {
        prototype: HTMLLeoFormElement;
        new (): HTMLLeoFormElement;
    };
    interface HTMLLeoSearchElement extends Components.LeoSearch, HTMLStencilElement {
    }
    var HTMLLeoSearchElement: {
        prototype: HTMLLeoSearchElement;
        new (): HTMLLeoSearchElement;
    };
    interface HTMLElementTagNameMap {
        "leo-button": HTMLLeoButtonElement;
        "leo-card": HTMLLeoCardElement;
        "leo-demo": HTMLLeoDemoElement;
        "leo-form": HTMLLeoFormElement;
        "leo-search": HTMLLeoSearchElement;
    }
}
declare namespace LocalJSX {
    interface LeoButton {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        "size"?: string;
        "type"?: string;
    }
    interface LeoCard {
        "first"?: string;
    }
    interface LeoDemo {
    }
    interface LeoForm {
        "first"?: string;
    }
    interface LeoSearch {
        "first"?: string;
    }
    interface IntrinsicElements {
        "leo-button": LeoButton;
        "leo-card": LeoCard;
        "leo-demo": LeoDemo;
        "leo-form": LeoForm;
        "leo-search": LeoSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "leo-button": LocalJSX.LeoButton & JSXBase.HTMLAttributes<HTMLLeoButtonElement>;
            "leo-card": LocalJSX.LeoCard & JSXBase.HTMLAttributes<HTMLLeoCardElement>;
            "leo-demo": LocalJSX.LeoDemo & JSXBase.HTMLAttributes<HTMLLeoDemoElement>;
            "leo-form": LocalJSX.LeoForm & JSXBase.HTMLAttributes<HTMLLeoFormElement>;
            "leo-search": LocalJSX.LeoSearch & JSXBase.HTMLAttributes<HTMLLeoSearchElement>;
        }
    }
}
