/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LeoButton {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface LeoSearch {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLLeoButtonElement extends Components.LeoButton, HTMLStencilElement {
    }
    var HTMLLeoButtonElement: {
        prototype: HTMLLeoButtonElement;
        new (): HTMLLeoButtonElement;
    };
    interface HTMLLeoSearchElement extends Components.LeoSearch, HTMLStencilElement {
    }
    var HTMLLeoSearchElement: {
        prototype: HTMLLeoSearchElement;
        new (): HTMLLeoSearchElement;
    };
    interface HTMLElementTagNameMap {
        "leo-button": HTMLLeoButtonElement;
        "leo-search": HTMLLeoSearchElement;
    }
}
declare namespace LocalJSX {
    interface LeoButton {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface LeoSearch {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "leo-button": LeoButton;
        "leo-search": LeoSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "leo-button": LocalJSX.LeoButton & JSXBase.HTMLAttributes<HTMLLeoButtonElement>;
            "leo-search": LocalJSX.LeoSearch & JSXBase.HTMLAttributes<HTMLLeoSearchElement>;
        }
    }
}
