// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'E:/LeoStar の 大前端之旅/最佳实践/leostar-ui/node_modules/dumi-theme-chakra/dist/builtins/Previewer/index.js';
