// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { SiteContext } from 'E:/LeoStar の 大前端之旅/最佳实践/leostar-ui/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {"name":"leostar-ui","version":"0.0.1"},
      historyType: "browser",
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      hostname: undefined,
      themeConfig: {"title":"leostar-ui组件库","footer":"Copyright © 2023 | Powered by LeoStar-UI","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"LeoStar-UI","carrier":"dumi","hd":true,"rtl":true,"social":{"github":{"name":"GitHub","link":"https://github.com/LeoStar-UI/leostar-ui","target":"_blank"}},"nav":[{"title":"指南","link":"/guide"},{"title":"组件","link":"/components/alert"},{"title":"团队","link":"/about/team"}]},
      _2_level_nav_available: true,
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
